name: first_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:            # â† harus diindent 2 spasi biar masuk ke dependencies
    sdk: flutter
  http: ^1.2.1        # versi http

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Untuk menambahkan aset ke aplikasi, tambahkan bagian 'assets' seperti ini:
  assets:
    # Aset gambar yang ingin kamu tambahkan harus diinduksikan dengan benar.
    # Pastikan spasi di depannya sesuai.
    - assets/images/hai.jpg

  # Untuk menambahkan font kustom ke aplikasi, tambahkan bagian 'fonts' di sini:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic